eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  application:
    name: schools
  data:
    mongodb:
      database: Schools
      port: 27017
      host: localhost

application:
  config:
    students_url: http://localhost:8222/api/v1/students
